// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rcteukovzyyoptebzffb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJjdGV1a292enl5b3B0ZWJ6ZmZiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Mzg1MzE2MjEsImV4cCI6MjA1NDEwNzYyMX0.jq_rWXteKxTyjrLQGyUm2Gz_VoZ-Oz-SdzPsnRx8osA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);